# Generated by Django 2.0 on 2018-09-20 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
            },
        ),
        migrations.RemoveField(
            model_name='moview_details',
            name='Genre',
        ),
        migrations.AddField(
            model_name='moview_details',
            name='Genre',
            field=models.ManyToManyField(to='rest_api.Genre'),
        ),
    ]
