# Generated by Django 2.0 on 2018-09-20 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_auto_20180920_0140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moview_details',
            options={},
        ),
        migrations.RemoveField(
            model_name='moview_details',
            name='Genre',
        ),
        migrations.AddField(
            model_name='moview_details',
            name='Genre',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
