# Generated by Django 2.0 on 2018-09-20 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_auto_20180920_0158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moview_details',
            name='Response',
        ),
    ]
